apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jenkins
  labels:
    app: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-nodeport
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: nginx-deployment
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30580
